# Change these first
owner: ItsNiceCraft # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ItsNiceCraft.EU
    url: https://itsnicecraft.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.itsnicecraft.eu
  # baseUrl: /status
  logoUrl: https://i.ibb.co/FHsqdYy/face.png
  name: Server Status
  introTitle: "**ItsNiceCraft Server Status**"
  # introMessage: This site displays the status of my services!
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: GitHub Issues
      href: https://github.com/$OWNER/$REPO/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
